#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ -e /boot/System.map-4.9.0-9-amd64 ]; then
	depmod -a -F /boot/System.map-4.9.0-9-amd64 4.9.0-9-amd64 || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d platform-modules-dx010 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
