#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/platform-modules-mystone" ]; then
	invoke-rc.d platform-modules-mystone stop || exit $?
fi
# End automatically added section
