# Celestica Platform modules

CEL_DX010_PLATFORM_MODULE_VERSION = 1.1
CEL_SILVERSTONE_PLATFORM_MODULE_VERSION = 1.1
CEL_MIDSTONE100TH2_PLATFORM_MODULE_VERSION = 1.1

export CEL_DX010_PLATFORM_MODULE_VERSION
export CEL_SILVERSTONE_PLATFORM_MODULE_VERSION
export CEL_MIDSTONE100TH2_PLATFORM_MODULE_VERSION

CEL_DX010_PLATFORM_MODULE = platform-modules-dx010_$(CEL_DX010_PLATFORM_MODULE_VERSION)_amd64.deb
$(CEL_DX010_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cel
$(CEL_DX010_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(CEL_DX010_PLATFORM_MODULE)_PLATFORM = x86_64-cel_seastone-r0
SONIC_DPKG_DEBS += $(CEL_DX010_PLATFORM_MODULE)

CEL_SILVERSTONE_PLATFORM_MODULE = platform-modules-silverstone_$(CEL_SILVERSTONE_PLATFORM_MODULE_VERSION)_amd64.deb
$(CEL_SILVERSTONE_PLATFORM_MODULE)_PLATFORM = x86_64-cel_silverstone-r0
$(eval $(call add_extra_package,$(CEL_DX010_PLATFORM_MODULE),$(CEL_SILVERSTONE_PLATFORM_MODULE)))

CEL_MIDSTONE100TH2_PLATFORM_MODULE = platform-modules-midstone100th2_$(CEL_MIDSTONE100TH2_PLATFORM_MODULE_VERSION)_amd64.deb
$(CEL_MIDSTONE100TH2_PLATFORM_MODULE)_PLATFORM = x86_64-cel_midstone_100th2-r0
$(eval $(call add_extra_package,$(CEL_DX010_PLATFORM_MODULE),$(CEL_MIDSTONE100TH2_PLATFORM_MODULE)))
